DATA:
  # 전체 데이터 기간
  START_DATE: '2001-01-01'
  END_DATE: '2024-08-01'
  
  # 데이터셋 분할
  TRAIN:
    START_DATE: '2001-01-01'
    END_DATE: '2017-12-31'
    RATIO: 0.7  # train/validation 분할 비율
  
  TEST:
    START_DATE: '2018-01-01'
    END_DATE: '2024-08-01'
  
  # 시퀀스 설정
  WINDOW_SIZE: 60  # 입력 시퀀스 길이 (이전 TRAIN_LEN)
  PRED_WINDOW: 20  # 예측 기간 (이전 PRED_LEN)
  
  # 데이터 처리
  N_STOCKS: 50  # 처리할 종목 수
  PROB_NORMALIZE: 'standardize'  # 확률값 정규화 방법 ['standardize', 'minmax']
  SCALING_FACTOR: 20  # 스케일링 팩터
USE_CUDA: true

MODEL:
  TYPE: 'TCN'  # ['GRU', 'TCN', 'TRANSFORMER']
  USE_PROB: false  # 확률 기반 모델 사용 여부
  N_STOCKS: 50  # 추가
  
  # GRU parameters
  N_LAYER: 1
  HIDDEN_DIM: 128
  DROPOUT: 0.3
  BIDIRECTIONAL: false
  
  # TCN parameters
  TCN:
    n_timestep: 60
    n_feature: 50  # n_stocks와 동일
    n_output: 50   # n_stocks와 동일
    kernel_size: 4
    n_dropout: 0.1
    hidden_size: 64
    level: 3
    num_channels: [64, 64, 64]    # channels 대신 num_channels 사용
  
  # TRANSFORMER parameters
  TRANSFORMER:
    n_timestep: 60
    n_output: 50 # n_stocks와 동일
    n_layer: 6
    n_head: 5
    n_dropout: 0.1

TRAINING:
  # 학습 파라미터
  BATCH_SIZE: 64
  EPOCHS: 50
  EARLY_STOPPING: 25
  LEARNING_RATE: 0.005
  MOMENTUM: 0.9
  
  # 하드웨어 설정
  USE_CUDA: true
  SEED: 42
  NUM_WORKERS: 32
  USE_DATA_PARALLEL: false
PORTFOLIO:
  # 목적함수 설정
  OBJECTIVE: 'sharpe_ratio'  # ['mean_variance', 'minimum_variance', 'sharpe_ratio']
  RISK_AVERSION: 1.0
  RISK_FREE_RATE: 0.02
  
  # 제약조건
  CONSTRAINTS:
    LONG_ONLY: true
    MAX_POSITION: 0.2
    MIN_POSITION: 0
    CARDINALITY: 50
    LEVERAGE: 1.0
  
  # 거래비용
  COSTS:
    TRANSACTION: 0.003
    MARKET_IMPACT: 0.001

BACKTEST:
  REBALANCING_FREQUENCY: 'monthly'  # ['daily', 'weekly', 'monthly', 'quarterly']
  WINDOW_SIZE: 60
  INCLUDE_TRANSACTION_COSTS: true
  RISK_METRICS: ['volatility', 'sharpe', 'sortino', 'max_drawdown']

PATHS:
  DATA:
    RAW: '/home/indi/codespace/ImagePortOpt/Data/raw_data'
    PROCESSED: '/home/indi/codespace/ImagePortOpt/Data/processed'
    DEEP: '/home/indi/codespace/ImagePortOpt/TS_Model/data'
  RESULTS: '/home/indi/codespace/ImagePortOpt/TS_Model/Result'
  MODELS: '/home/indi/codespace/ImagePortOpt/TS_Model/models'