DATA:
  # 전체 데이터 기간
  START_DATE: '2001-01-01'
  END_DATE: '2024-08-01'
  
  # 데이터셋 분할
  TRAIN:
    START_DATE: '2001-01-01'
    END_DATE: '2017-12-31'
    RATIO: 0.7  # train/validation 분할 비율
  
  TEST:
    START_DATE: '2018-01-01'
    END_DATE: '2024-08-01'
  
  # 시퀀스 설정
  WINDOW_SIZE: 60  # 입력 시퀀스 길이 (이전 TRAIN_LEN)
  PRED_WINDOW: 60  # 예측 기간 (이전 PRED_LEN)
  
  # 데이터 처리
  N_STOCKS: 500  # 처리할 종목 수
  PROB_NORMALIZE: 'standardize'  # 확률값 정규화 방법 ['standardize', 'minmax']
  SCALING_FACTOR: 60  # 스케일링 팩터
USE_CUDA: true

MODEL:
  TYPE: 'TCN'  # ['GRU', 'TCN', 'TRANSFORMER']
  USEPROB: false
  NSTOCKS: 50
  
  # GRU parameters
  N_LAYER: 1
  HIDDEN_DIM: 128
  DROPOUT: 0.4
  BIDIRECTIONAL: false
  
  # TCN parameters
  TCN:
    n_timestep: 60 # WINDOW_SIZE
    n_feature: 500  # N_STOCKS
    n_output: 500 # N_STOCKS
    kernel_size: 8  # 4 -> 8
    n_dropout: 0.2  # 0.1 -> 0.2
    hidden_size: 128  # 64 -> 128
    level: 5  # 3 -> 5
    num_channels: [64, 128, 256, 128, 64]  # 더 복잡한 채널 구조
  
  # TRANSFORMER parameters
  TRANSFORMER:
    n_timestep: 60 # WINDOW_SIZE
    n_output: 500  # N_STOCKS
    n_layer: 4
    n_head: 5
    n_dropout: 0.1

TRAINING:
  # 학습 파라미터
  BATCH_SIZE: 64
  EPOCHS: 1
  EARLY_STOPPING: 50
  LEARNING_RATE: 0.005
  MOMENTUM: 0.9
  
  # 하드웨어 설정
  USE_CUDA: true
  SEED: 42
  NUM_WORKERS: 32
  USE_DATA_PARALLEL: false
PORTFOLIO:
  # 목적함수 설정
  OBJECTIVE: 'maxsharpe'  # max_sharpe -> maxsharpe
  # ['meanvar', 'minvar', 'maxsharpe']
  RISKAVERSION: 1.0   # RISK_AVERSION -> RISKAVERSION
  RISKFREERATE: 0.02  # RISK_FREE_RATE -> RISKFREERATE
  
  # 제약조건
  CONSTRAINTS:
    LONG_ONLY: true
    MAX_POSITION: 0.2
    MIN_POSITION: 0
    CARDINALITY: 50
    LEVERAGE: 1.0
  
  # 거래비용
  COSTS:
    TRANSACTION: 0.003
    MARKET_IMPACT: 0.001

BACKTEST:
  REBALANCING_FREQUENCY: 'quarterly'  # ['daily', 'weekly', 'monthly', 'quarterly']
  WINDOW_SIZE: 60
  INCLUDE_TRANSACTION_COSTS: true
  RISK_METRICS: ['volatility', 'sharpe', 'sortino', 'max_drawdown']

PATHS:
  DATA:
    RAW: '/home/indi/codespace/ImagePortOpt/Data/raw_data'
    PROCESSED: '/home/indi/codespace/ImagePortOpt/Data/processed'
    DEEP: '/home/indi/codespace/ImagePortOpt/TS_Model/data'
  RESULTS: '/home/indi/codespace/ImagePortOpt/TS_Model/Result'
  MODELS: '/home/indi/codespace/ImagePortOpt/TS_Model/models'