# data
START: '2001-01-01'
END: '2024-08-01'
LEN_DATA: 5000

# model parameter
N_STOCK: 100
TRAIN_LEN: 60
PRED_LEN: 20

# 데이터 설정
TRAIN_START_DATE: '2001-01-01' # In Sample
TRAIN_END_DATE: '2017-12-31' # In Sample
TRAIN_RATIO: 0.7
VALIDATION_RATIO: 0.3

TEST_START_DATE: '2018-01-01' # Out of Sample
TEST_END_DATE: '2024-08-01' # Out of Sample
RESULT_DIR: 'Result'

# model selection
MODEL: 'GRU'
USE_PROB: true  # 확률 기반 모델 사용 여부

# learning parameter
BATCH: 32
EPOCHS: 500
EARLY_STOP: 50
LR: 0.005
MOMENTUM: 0.9
USE_CUDA: true
SEED: 42

# Portfolio Optimization Settings
PORTFOLIO:
  # 목적함수 설정
  OBJECTIVE: 'sharpe_ratio'  # ['mean_variance', 'minimum_variance', 'sharpe_ratio']
  RISK_AVERSION: 1.0  # mean-variance 목적함수용 위험회피계수
  RISK_FREE_RATE: 0.02  # Sharpe ratio 계산용 무위험 수익률 (연율화)
  
  # 포트폴리오 제약조건
  CONSTRAINTS:
    LONG_ONLY: true  # 롱온리 제약
    MAX_POSITION: 0.2  # 최대 포지션 제약 (0.2 = 20%)
    MIN_POSITION: 0.0  # 최소 포지션 제약
    CARDINALITY: null  # 포트폴리오 내 종목 수 제약
    LEVERAGE: 1.0  # 레버리지 제약 (1.0 = 100%)
  
  # 거래비용 설정
  TRANSACTION_COST: 0.003  # 거래비용 (0.003 = 0.3%)
  MARKET_IMPACT: 0.001  # 시장충격비용 (0.001 = 0.1%)

# GRU parameters
N_LAYER: 1
HIDDEN_DIM: 128
N_HEAD: 10
N_FEAT: 100
DROPOUT: 0.3
BIDIRECTIONAL: false

# TCN parameters
TCN:
  n_timestep: 60
  n_output: 100
  kernel_size: 4
  n_dropout: 0.1
  hidden_size: 64
  level: 3
  channels: [64, 64, 64]

# TRANSFORMER parameters
TRANSFORMER:
  n_timestep: 60
  n_output: 100
  n_layer: 6
  n_head: 5
  n_dropout: 0.1

# 백테스트 설정
BACKTEST:
  REBALANCING_FREQUENCY: 'monthly'  # ['daily', 'weekly', 'monthly', 'quarterly']
  WINDOW_SIZE: 60  # 백테스트시 사용할 룩백 기간
  INCLUDE_TRANSACTION_COSTS: true  # 거래비용 포함 여부
  RISK_METRICS: ['volatility', 'sharpe', 'sortino', 'max_drawdown']  # 계산할 위험 지표들 