# data
START: '2001-01-01'
END: '2024-08-01'
LEN_DATA: 5000

# model parameter
N_STOCK: 100
TRAIN_LEN: 60
PRED_LEN: 20

# 데이터 설정
TRAIN_START_DATE: '2001-01-01' # In Sample
TRAIN_END_DATE: '2017-12-31' # In Sample
TRAIN_RATIO: 0.7
VALIDATION_RATIO : 0.3

TEST_START_DATE: '2018-01-01' # Out of Sample
TEST_END_DATE: '2024-08-01' # Out of Sample
RESULT_DIR: 'Result'

# model selection
MODEL: 'GRU'

# learning parameter
BATCH: 32
EPOCHS: 500
EARLY_STOP: 50
LR: 0.005
MOMENTUM: 0.9
USE_CUDA: true
SEED: 42

# portfolio optimization function (loss)
LB: 0
UB: 0.2
LOSS_FUNCTION: 'max_sharpe'

# GRU parameters
N_LAYER: 1
HIDDEN_DIM: 128
N_HEAD: 10
N_FEAT: 100
DROPOUT: 0.3
BIDIRECTIONAL: false

# TCN parameters
TCN:
  n_timestep: 60
  n_output: 100
  kernel_size: 4
  n_dropout: 0.1
  hidden_size: 64
  level: 3
  channels: [64, 64, 64]

# TRANSFORMER parameters
TRANSFORMER:
  n_timestep: 60
  n_output: 100
  n_layer: 6
  n_head: 5
  n_dropout: 0.1