# data
START: '2001-01-01'
END: '2024-08-01'
LEN_DATA: 6000

# make_image
window_size: 60
volume_bar: true
ma_lags: [5, 20, 60]
chart_type: "bar"
year: 2024
freq: "month"
SIZE_DICT:
  5: [32, 15]
  20: [64, 60]
  60: [96, 180]
  120: [128, 360]

# model parameter
N_STOCK: 4231  # 입력 주식 수
'M': 50
TRAIN_LEN: 60
PRED_LEN: 20

# 데이터 설정
TRAIN_START_DATE: '2001-01-01' # In Sample
TRAIN_END_DATE: '2017-12-31' # In Sample
VALIDATION_RATIO: 0.2

TEST_START_DATE: '2018-01-01' # Out of Sample
TEST_END_DATE: '2024-08-01' # Out of Sample
RESULT_DIR: 'Result'

# model parameter
MODELS: ['GRU', 'TCN', 'TRANSFORMER']
MULTIMODAL_OPTIONS: [false]
LOSS_FUNCTIONS: ['max_sharpe']
TRAIN_LEN_OPTIONS: [60]
PRED_LEN_OPTIONS: [20]
SEED: 42

# learning parameter
BATCH: 128
EPOCHS: 50
EARLY_STOP: 2
MIN_DELTA: 0.0001
LR: 0.005
MOMENTUM: 0.9
USE_CUDA: true

# portfolio optimization function (loss)
LB: 0
UB: 0.2
N_FEAT: 50 # Best 50 in N_STOCK
BETA: 0.2
LOSS_FUNCTION: 'max_sharpe'

# model parameter
TCN:
  n_timestep: 60 # TRAIN_LEN
  n_output: 50 # Best 50 in N_STOCK
  kernel_size: 4
  n_dropout: 0.1
  hidden_size: 64
  level: 3

GRU:
  n_layers: 1
  hidden_dim: 128
  dropout_p: 0.3
  bidirectional: false
  n_output: 50 # Best 50 in N_STOCK

TRANSFORMER:
  n_timestep: 60 # TRAIN_LEN
  n_output: 50 # Best 50 in N_STOCK
  n_layer: 6
  n_head: 5
  n_dropout: 0.1
