# data
START: '2001-01-01'
END: '2024-08-01'
LEN_DATA: 5000

# model parameter
N_STOCK: 313
N_SELECT: 50  # 실제 투자할 종목 수
TRAIN_LEN: 60
PRED_LEN: 20

# 데이터 설정
TRAIN_START_DATE: '2001-01-01' # In Sample
TRAIN_END_DATE: '2017-12-31' # In Sample
TRAIN_RATIO: 0.7
VALIDATION_RATIO : 0.3

TEST_START_DATE: '2018-01-01' # Out of Sample
TEST_END_DATE: '2024-08-01' # Out of Sample
RESULT_DIR: 'Result'

# model selection
MODEL: 'GRU'  # 현재 선택된 모델

# learning parameter
BATCH: 128
EPOCHS: 500  # 500으로 수정
EARLY_STOP: 50  # 50으로 수정
LR: 0.001
MOMENTUM: 0.9
USE_CUDA: true
SEED: 42

# portfolio optimization function (loss)
LB: 0
UB: 0.5
LOSS_FUNCTION: 'max_sharpe'

# GRU parameters
N_LAYER: 1          # 레이어 수 증가
HIDDEN_DIM: 128     # hidden dimension 증가 (n_stocks보다 크게)
N_HEAD: 10
N_FEAT: 313        # n_stocks와 동일하게 설정
DROPOUT: 0.3
BIDIRECTIONAL: false # bidirectional 사용으로 특성 추출 강화

# TCN parameters
TCN:
  n_timestep: 60
  n_output: 313
  kernel_size: 4
  n_dropout: 0.1
  hidden_size: 64
  level: 3
  channels: [64, 64, 64]

# TRANSFORMER parameters
TRANSFORMER:
  n_timestep: 60
  n_output: 313  # N_STOCK과 동일하게 수정
  n_layer: 6
  n_head: 5
  n_dropout: 0.1