# config.yaml

# data
START: '2001-01-01'
END: '2024-09-01'
LEN_DATA: 6000

# make_image
window_size: 60
volume_bar: true
ma_lags: [5, 20, 60]
chart_type: "bar"
year: 2024
freq: "month"
SIZE_DICT:
  5: [32, 15]
  20: [64, 60]
  60: [96, 180]
  120: [128, 360]

# model parameter
N_STOCK: 500
TRAIN_LEN: 60
PRED_LEN: 20
TRAIN_RATIO: 0.60
VAL_RATIO: 0.20
TEST_RATIO: 0.20
RESULT_DIR: 'result'

# model parameter
MODELS: ['GRU', 'TCN', 'TRANSFORMER']
MULTIMODAL_OPTIONS: [false]
LOSS_FUNCTIONS: ['max_sharpe']
TRAIN_LEN_OPTIONS: [60]
PRED_LEN_OPTIONS: [20]
SEED: 42

# learning parameter
BATCH: 32
EPOCHS: 500
EARLY_STOP: 20
MIN_DELTA: 0.0001
LR: 0.005
MOMENTUM: 0.9
USE_CUDA: true

# portfolio optimization function (loss)
LB: 0
UB: 0.2
N_FEAT: 50 # Best 50 in N_STOCK
BETA: 0.2
LOSS_FUNCTION: 'max_sharpe'

# model parameter
TCN:
  n_timestep: 60 # TRAIN_LEN
  n_output: 50 # Best 50 in N_STOCK
  kernel_size: 4
  n_dropout: 0.1
  hidden_size: 64
  level: 3

GRU:
  n_layers: 1
  hidden_dim: 128
  dropout_p: 0.3
  bidirectional: false

TRANSFORMER:
  n_timestep: 60 # TRAIN_LEN
  n_output: 50 # Best 50 in N_STOCK

  n_layer: 6
  n_head: 5
  n_dropout: 0.1
  
